# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: esc.sh
description: "Mansoor A, Site Reliability Engineer"
keywords: "sysadmin, engineer, linux, devops, SRE, blog, web"
url: https://esc.sh
baseurl: ""

#google_analytics: UA-52446115-1
repo: http://github.com/mansoormajeed/landing-page
#disqus_shortname: "nandothemes"
#disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Mansoor A
  job: Site Reliability Engineer
  bio: "Full time Linux geek, part time traveller, martial artist, (motor)cyclist"
  thumb: /images/author.jpg
  email: me@esc.sh
  url: https://esc.sh/
  github: https://github.com/mansoormajeed
  twitter: https://twitter.com/manzmajeed
  facebook: https://facebook.com/manz.majeed
  linkedin: https://linkedin.com/in/mansoormajeed

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: travel
    title: Travel
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
